# Generated by Django 4.0.4 on 2022-05-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_name_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_tag',
        ),
    ]
